Update Run_AMI.yml

diff --git a/.github/workflows/Run_AMI.yml b/.github/workflows/Run_AMI.yml
--- a/.github/workflows/Run_AMI.yml
+++ b/.github/workflows/Run_AMI.yml
@@ -36,8 +36,24 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       - name: Apply Terraform
+        id: apply
         run: terraform apply -auto-approve -input=false
         env:
           TF_VAR_AMI_ID: ${{ secrets.AMI_ID }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+      - name: Collect status
+        id: collect_status
+        run: |
+          echo "TERRAFORM_STATUS=$([[ '${{ steps.apply.outcome }}' == 'success' ]] && echo '✅ Success' || echo '❌ Failed')" >> $GITHUB_ENV
+
+      - name: Send Telegram Notification
+        if: always()
+        uses: cbrgm/telegram-github-action@v1
+        with:
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          to: ${{ secrets.TELEGRAM_CHAT_ID }}
+          message: |
+            *AMI Id*: ${{ secrets.AMI_ID }}
+            *Terraform Apply Status*: ${{ env.TERRAFORM_STATUS }}
